language: java
addons:
  sonarcloud:
    organization: "nickmanbear"
    token:
      secure: GmwmwUoq+OS2fSPIsMYK1AaNSfY5cO0N5UcHAGwXJX0lr3JC0vPZk6NQ6T5nR/S8VBkajS12W4K7uWFh1276ggkiR+ulg4PdTzovbe741Jn6+5+4/7CbyT7YI+6VEpCgaMpEvZgfCb4AaevirYNbYKlJb1/2Bhdf6rHLXFQ/Y0ocxXUMHzSppVhlG5sif0PYkP79FmH/UwsonErmS7Y3jyVRo+MCx6E91zxhtRS3F4B8cyXNczw74VCD/bRwUHdh85M9oB4qKlxi9cI0IvNvFL9e3KY00IqjeaH35C2IoTtA4nH/1fb55G8mHBPWW53cLpb0hL+dXgdRcMJy46SyzRu1nq205SzQt/SN03r290Jiqv1eu+96omFoZO8feV6CqTjJuMMy43IFTWH26UKiemBAdbTIYw5cFgRjVnIVcUH2dZ+vAxwPnzv0nI/9RTGHEp8IoXYkGl97DBj5/M9Cg1kHHobeNunIsUp1dcFxT9qnKXEVUAB1BdsuadlVqzt4SqGL51qFjKjz8JOnxf0POJ+Kvhti3oDYSCK4kFVC1lOKLi4dWcTKy3r+t7E3LUztAI3Aaq8mASoBgcDcTSBXTUqOegSGtZDgNV1dmS/cMfjlue2akunQp9sHejxBBPjYsoW3PNrNza4B/rTRWq1NyO0Meu+FyXYxH6Io7KG2Epg=
script:
  - ./gradlew sonarqube
deploy: 
  provider: heroku
  api_key:
    secure: KuXXMetv63DDr1vpE+sif/JFIdXKQB0tDsqxONHaf5X7Wwfc7/QWPXROdmSKE7mWtaMqjJVodcYxAv/15zgTR2o73WogvOI+4762sqUp2XcFJPLJsArCDhDSMH9nvOSQaKofIsuB8FIbcDrHbBvJVcE+5RWNcv8SsutnzpIAc0GDzizsW+bYEfWX5bKi/iAye5C9zY/qu/oKVNAJ+JSVrVthzkGQHd9AI8WervZ9h9SeT/8ekzY6wFiPQlrdV9MV+X8r26Pa7zZNDm5yaPbLvG/aVxna9qR+F4bqvav4oE9AzGeKHwdhxcea5pqq/YBuQfLk4PEml//FdIsmUdpJvAzkaD5AJImTjNvDyGEdnYiDIqyzT7Ity7hlYEsBCSaXrROh+I0GM04a53DS8sUcT8RnpLgX2Ey26fQJXuwJHAOJjEJq6pylGG2WthBBZQBgO+Qz+JwtrNvuKeIKX57RExbv0K7oDrQBET5ztfOI15lTt2mbITBWJh61hjpLrNukPbcZjgRU0XOVF2GoD80fnkfEy1ZFbN9t7MPG00kYTM58eaOkh23L0l/cfNlFbieEGeD9QyoVVetRgGiNiPkf9VP5yaoYQ2C1UZNPXUj2UFVKlKHCrefzAKBgMQyDtULULFTxZRo+JE7mO2hKUFYD0+nhrkyb9+lBWh6/RkgVLx0=
  app: spryng-example
